#Configurations
Debug: off
AutoSave: 12000
Connection: "mongodb://localhost"
HasLogin: false
User: ""
Pass: ""
Ecos:
  - "Default"
  - "Tokens"
DefaultEco: "Default"
Prestiges:
  A:
    Price: 100
    Name: "A"
    Cmds:
      - ""