name: McEngine
main: me.alexirving.core.McEngine
version: 1.0
description: Main core for plugins.
depend: [ ProtocolLib ]
authors: [ Alexirving ]
commands:
  Admin:
    permission: mcengine.admin
  GetItem:
  tool:
  Animation:
    permission: mcengine.animation.useObfuscate
  McEngineReloadCMD:
    permission: mcengine.reload
softdepend: [ WorldEdit, PlaceholderAPI, Vault ]