name: McEngine
main: me.alexirving.core.McEngine
version: 1.0
api-version: 1.13
description: Main core for plugins.
depend: [ ProtocolLib ]
authors: [ Alexirving ]
softdepend:
  - "WorldEdit"
  - "PlaceholderAPI"
  - "Vault"