FrameDelay: 1 #Delay between each frame (In ticks)
Stands:
  A: ARMOR_STAND
  B: ARMOR_STAND
  C: ARMOR_STAND
  D: ARMOR_STAND
  E: ARMOR_STAND
  F: ARMOR_STAND
  G: ARMOR_STAND
  H: ARMOR_STAND
Frames:
  - "SetItem(A;4;Skull)|DrawLine(Tp(A;[X,Y,Z]);9;[0,0,0];[0,1,0])"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "SetItem(B;4;Skull)|DrawLine(Tp(B;[X,Y,Z]);9;[0,0,0];[0,1,0])|DrawLine(Tp(A;[X,Y,Z]);9;[0,1,0];[-1.06066017178,1.06066017178,0])"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "DrawLine(Tp(B;[X,Y,Z]);9;[0,1,0];[-1.06066017178,1.06066017178,0])|DrawCircle(Tp(A;[X,Y,0]);[0,0,0];[-1.06066017178,1.06066017178,0];-405;78)|SetItem(C;4;Skull)|DrawLine(Tp(C;[X,Y,Z]);9;[0,0,0];[0,1,0])"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "DrawCircle(Tp(B;[X,Y,0]);[0,0,0];[-1.06066017178,1.06066017178,0];-360;69)|DrawLine(Tp(C;[X,Y,Z]);9;[0,1,0];[-1.06066017178,1.06066017178,0])|SetItem(D;4;Skull)|DrawLine(Tp(D;[X,Y,Z]);9;[0,0,0];[0,1,0])"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "DrawCircle(Tp(C;[X,Y,0]);[0,0,0];[-1.06066017178,1.06066017178,0];-315;60)|DrawLine(Tp(D;[X,Y,Z]);9;[0,1,0];[-1.06066017178,1.06066017178,0])|SetItem(E;4;Skull)|DrawLine(Tp(E;[X,Y,Z]);9;[0,0,0];[0,1,0])"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "DrawCircle(Tp(D;[X,Y,0]);[0,0,0];[-1.06066017178,1.06066017178,0];-270;51)|DrawLine(Tp(E;[X,Y,Z]);9;[0,1,0];[-1.06066017178,1.06066017178,0])|SetItem(F;4;Skull)|DrawLine(Tp(F;[X,Y,Z]);9;[0,0,0];[0,1,0])"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "DrawCircle(Tp(E;[X,Y,0]);[0,0,0];[-1.06066017178,1.06066017178,0];-225;42)|DrawLine(Tp(F;[X,Y,Z]);9;[0,1,0];[-1.06066017178,1.06066017178,0])|SetItem(G;4;Skull)|DrawLine(Tp(G;[X,Y,Z]);9;[0,0,0];[0,1,0])"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "DrawCircle(Tp(F;[X,Y,0]);[0,0,0];[-1.06066017178,1.06066017178,0];-180;33)|DrawLine(Tp(G;[X,Y,Z]);9;[0,1,0];[-1.06066017178,1.06066017178,0])|SetItem(H;4;Skull)|DrawLine(Tp(H;[X,Y,Z]);9;[0,0,0];[0,1,0])"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "DrawCircle(Tp(G;[X,Y,0]);[0,0,0];[-1.06066017178,1.06066017178,0];-135;24)|DrawLine(Tp(H;[X,Y,Z]);9;[0,1,0];[-1.06066017178,1.06066017178,0])"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "DrawCircle(Tp(H;[X,Y,0]);[0,0,0];[-1.06066017178,1.06066017178,0];-90;15)"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Kill(A)"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Kill(B)"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Kill(D)"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Kill(E)"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Kill(F)"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Kill(G)"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Kill(H)"
  - "DrawLine(Tp(C;[X,Y,Z]);9;[0,1.5,0];[0,1,0])"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "Empty()"
  - "SetDisplayName(C;&kShmeziDev)"
  - "Loop(Empty();100)"